// library-stub-e2e.test.ts — FORGE-S35-T04 (Slice 3)
//
// End-to-end contract test for the fixed 10-doc KB surface + the confident
// not-applicable stub policy. Unlike verifiers.test.ts (which mocks
// execFileAsync), this test spawns the REAL bundled verify-phase.cjs from the
// built dist payload against a library-shaped KB fixture materialized on disk.
//
// Library shape = no persistence, no routing, no deployment. Those three docs
// are confident `status: not-applicable` stubs; the other seven are substantive.
// The contract: all 10 canonical docs exist AND `verify-phase.cjs --phase 2`
// exits 0 — completeness stays advisory (an entity-less/library project passes).
//
// Requires `npm run build` first so dist/forge-payload/tools/verify-phase.cjs
// reflects the current plugin source (the CI test script builds before test).

import { spawnSync } from "node:child_process";
import * as fs from "node:fs";
import * as os from "node:os";
import * as path from "node:path";
import { afterEach, beforeEach, describe, expect, it } from "vitest";

// __dirname = forge-cli/test/extensions/forgecli/forge-init
const VERIFY_PHASE = path.resolve(
	import.meta.dirname,
	"../../../../dist/forge-payload/tools/verify-phase.cjs",
);

// The canonical 10-doc KB contract (FORGE-S35-T01). Kept in lockstep with
// verify-phase.cjs ARCH_DOCS via the plugin's kb-doc-contract.test.cjs.
const CANONICAL_DOCS = [
	"architecture/stack",
	"architecture/processes",
	"architecture/routing",
	"architecture/database",
	"architecture/testing",
	"architecture/deployment",
	"architecture/entity-model",
	"architecture/stack-checklist",
	"business-domain/domain-model",
	"business-domain/domain-concepts",
];

// A library-shaped project: no persistence, no routing surface, no deployment.
const STUB_DOCS = new Set([
	"architecture/database",
	"architecture/routing",
	"architecture/deployment",
]);

const CONFIDENT_STUB_HEADER =
	"<!-- AUTO-GENERATED by /forge:init — confidence: 100% — status: not-applicable -->";

/** Materialize a library-shaped KB: 3 confident not-applicable stubs, 7 substantive docs. */
function writeLibraryKb(root: string, kbPath = "engineering"): void {
	for (const docId of CANONICAL_DOCS) {
		const abs = path.join(root, kbPath, ...docId.split("/")) + ".md";
		fs.mkdirSync(path.dirname(abs), { recursive: true });
		const heading = docId.slice(docId.lastIndexOf("/") + 1);
		const content = STUB_DOCS.has(docId)
			? `${CONFIDENT_STUB_HEADER}\n# ${heading}\nNot applicable — this library exposes no ${heading} surface.\n`
			: `<!-- AUTO-GENERATED by /forge:init — confidence: 90% -->\n# ${heading}\nSubstantive ${heading} content derived from discovery.\n`;
		fs.writeFileSync(abs, content, "utf8");
	}
}

describe("library-shaped KB stub-policy e2e (FORGE-S35-T04)", () => {
	let tmp: string;
	beforeEach(() => {
		tmp = fs.mkdtempSync(path.join(os.tmpdir(), "lib-kb-e2e-"));
	});
	afterEach(() => {
		fs.rmSync(tmp, { recursive: true, force: true });
	});

	it("the built dist payload verify-phase.cjs exists", () => {
		expect(fs.existsSync(VERIFY_PHASE)).toBe(true);
	});

	it("materializes all 10 canonical docs with database/routing/deployment as confident stubs", () => {
		writeLibraryKb(tmp);
		for (const docId of CANONICAL_DOCS) {
			const abs = path.join(tmp, "engineering", ...docId.split("/")) + ".md";
			expect(fs.existsSync(abs), `expected ${docId}.md to exist`).toBe(true);
		}
		for (const docId of STUB_DOCS) {
			const abs = path.join(tmp, "engineering", ...docId.split("/")) + ".md";
			const src = fs.readFileSync(abs, "utf8");
			expect(src, `${docId} should be a confident not-applicable stub`).toMatch(
				/confidence:\s*100%/i,
			);
			expect(src, `${docId} should carry the status: not-applicable marker`).toMatch(
				/status:\s*not-applicable/i,
			);
		}
	});

	it("verify-phase.cjs --phase 2 exits 0 for the library-shaped KB", () => {
		writeLibraryKb(tmp);
		const r = spawnSync("node", [VERIFY_PHASE, "--phase", "2", "--kb-path", "engineering"], {
			cwd: tmp,
			encoding: "utf8",
		});
		expect(r.status, `expected exit 0, got ${r.status}. stdout: ${r.stdout}`).toBe(0);
	});

	it("rejects the same KB when a stub is degraded to a header-only doc (regression guard)", () => {
		writeLibraryKb(tmp);
		// Strip database.md down to just its confidence header — no marker, no body.
		const dbDoc = path.join(tmp, "engineering", "architecture", "database.md");
		fs.writeFileSync(dbDoc, "<!-- AUTO-GENERATED by /forge:init — confidence: 100% -->\n", "utf8");
		const r = spawnSync("node", [VERIFY_PHASE, "--phase", "2", "--kb-path", "engineering"], {
			cwd: tmp,
			encoding: "utf8",
		});
		expect(r.status, "header-only stub must fail the gate").toBe(1);
		const out = JSON.parse(r.stdout);
		expect(out.missing.some((m: string) => m.includes("database"))).toBe(true);
	});
});
