// lib/versions.ts — consolidated version-reader utilities (B-1).
//
// Centralises the version-reading helpers that were duplicated between
// `src/extensions/forgecli/index.ts` (readPkgVersions) and
// `src/bin/forge.ts` (readForgeCliPkg / readPiVersion / readBundledPluginVersion).
//
// All functions accept a `pkgRoot` parameter — the resolved package root
// directory — so each caller can pass in the root it has already resolved
// via `import.meta.url` or `__dirname`. This avoids embedding `import.meta.url`
// inside the lib module (which would resolve to the lib's own directory,
// not the package root).

import * as fs from "node:fs";
import * as path from "node:path";
import { fileURLToPath } from "node:url";

/** Minimal shape of the forgecli `package.json`. */
interface ForgePkg {
	version?: string;
	forge?: {
		bundledVersion?: string;
	};
}

/**
 * Reads the forgecli `package.json` from the given package root.
 * Returns `{ version: "unknown" }` on any error.
 */
export function readForgeCliPkg(pkgRoot: string): ForgePkg {
	try {
		const pkgPath = path.join(pkgRoot, "package.json");
		const raw = fs.readFileSync(pkgPath, "utf8");
		return JSON.parse(raw) as ForgePkg;
	} catch {
		return { version: "unknown" };
	}
}

/**
 * Returns the forgecli package version string.
 * Returns `"unknown"` when `package.json` cannot be read or is missing a
 * `version` field.
 */
export function readForgeCliVersion(pkgRoot: string): string {
	const pkg = readForgeCliPkg(pkgRoot);
	return typeof pkg.version === "string" && pkg.version.length > 0 ? pkg.version : "unknown";
}

/**
 * Returns the bundled Forge plugin version.
 *
 * Primary source: `<pkgRoot>/dist/forge-payload/.claude-plugin/plugin.json`,
 * regenerated by `scripts/build-payload.cjs` on every build — single source
 * of truth that never drifts.
 *
 * Fallback: `package.json`'s `forge.bundledVersion` mirror (hand-maintained,
 * used in dev / pre-build environments).
 *
 * Returns `"unknown"` when neither source is available.
 */
export function readBundledPluginVersion(pkgRoot: string): string {
	try {
		const pluginJsonPath = path.join(pkgRoot, "dist", "forge-payload", ".claude-plugin", "plugin.json");
		const pluginPkg = JSON.parse(fs.readFileSync(pluginJsonPath, "utf8")) as { version?: string };
		if (typeof pluginPkg.version === "string" && pluginPkg.version.length > 0) {
			return pluginPkg.version;
		}
	} catch {
		// Fall through to package.json mirror.
	}
	const pkg = readForgeCliPkg(pkgRoot);
	return pkg.forge?.bundledVersion ?? "unknown";
}

/**
 * Asynchronously resolves the pi-coding-agent version by finding its
 * `package.json` via `import.meta.resolve`.
 *
 * Returns `"unknown"` when the resolution fails (e.g. the package is not
 * installed or bundled).
 */
export async function readPiVersionAsync(): Promise<string> {
	try {
		const piEntryUrl = import.meta.resolve("@earendil-works/pi-coding-agent");
		const piDir = path.dirname(fileURLToPath(piEntryUrl));
		const pkgPath = path.resolve(piDir, "..", "package.json");
		const raw = fs.readFileSync(pkgPath, "utf8");
		const pkg = JSON.parse(raw) as { version?: string };
		return pkg.version ?? "unknown";
	} catch {
		return "unknown";
	}
}

/**
 * Synchronously reads both the CLI and bundled plugin versions.
 *
 * Intended for use at module load time where async is not available (e.g.
 * `const PKG_VERSIONS = readPkgVersionsSync(pkgRoot)` at the top level of
 * an ES module).
 *
 * Returns empty strings `""` on any read failure so that callers can use
 * falsy checks (`if (cliVersion && bundledForgeVersion)`) to gate
 * version-dependent features. Distinct from `readForgeCliVersion` which
 * returns `"unknown"` — the two have different sentinel conventions.
 */
export function readPkgVersionsSync(pkgRoot: string): { cliVersion: string; bundledForgeVersion: string } {
	try {
		const pkg = readForgeCliPkg(pkgRoot);
		const cliVersion = typeof pkg.version === "string" && pkg.version.length > 0 ? pkg.version : "";

		let bundledForgeVersion = "";
		try {
			const pluginJsonPath = path.join(pkgRoot, "dist", "forge-payload", ".claude-plugin", "plugin.json");
			const pluginPkg = JSON.parse(fs.readFileSync(pluginJsonPath, "utf8")) as { version?: unknown };
			bundledForgeVersion = typeof pluginPkg.version === "string" ? pluginPkg.version : "";
		} catch {
			// Payload not built — fall back to package.json mirror.
			bundledForgeVersion = typeof pkg.forge?.bundledVersion === "string" ? pkg.forge.bundledVersion : "";
		}

		return { cliVersion, bundledForgeVersion };
	} catch {
		return { cliVersion: "", bundledForgeVersion: "" };
	}
}
